exec-once = /usr/libexec/xdg-desktop-portal-wlr &
exec-once = wlr-randr --output HDMI-A-1 --preferred --left-of DP-2 --output DP-2 --mode 3440x1440@143.923004 --adaptive-sync enabled
#exec-once = wlr-randr --output DP-2 --mode 3440x1440@143.923004 --pos 2560,0 --adaptive-sync enabled
#exec-once = swww-daemon &
#exec-once = eval $(dbus-launch --sh-syntax) &
#exec-once = pipewire &
#exec-once = pipewire-pulse &
#exec-once = wireplumber &
#exec-once = waybar &
#exec-once = swaync &
exec-once = /usr/libexec/polkit-mate-authentication-agent-1 &
exec-once = wl-paste --watch cliphist store &
exec-once = qs -c noctalia-shell &

