env=MOZ_ENABLE_WAYLAND,1
env=MOZ_DBUS_REMOTE,1
env=XDG_SESSION_TYPE,wayland
env=XDG_CURRENT_DESKTOP,wlroots
env=XDG_SESSION_DESKTOP,wlroots
env=EGL_PLATFORM,wayland
env=CLUTTER_BACKEND,wayland

env=QT_QPA_PLATFORMTHEME,qt6ct
env=QT_STYLE_OVERRIDE,Fusion
env=QT_FONT_DPI,96
env=QT5_QPA_PLATFORMTHEME,qt5ct
env=QT_AUTO_SCREEN_SCALE_FACTOR,1
env=QT_QPA_PLATFORM,Wayland;xcb
env=QT_WAYLAND_FORCE_DPI,physical

env=GDK_BACKEND,wayland,x11,*


exec-once = /usr/libexec/xdg-desktop-portal-wlr &
exec-once = wlr-randr --output HDMI-A-1 --preferred --left-of DP-2 --output DP-2 --mode 3440x1440@143.923004 --adaptive-sync enabled
#exec-once = wlr-randr --output DP-2 --mode 3440x1440@143.923004 --pos 2560,0 --adaptive-sync enabled
exec-once = swww-daemon &
exec-once = eval $(dbus-launch --sh-syntax) &
exec-once = pipewire &
#exec-once = pipewire-pulse &
#exec-once = wireplumber &
exec-once = wl-paste --watch cliphist store &
exec-once = waybar &
exec-once = swaync &
exec-once = swayosd-server &
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1 &
exec-once = wl-paste --watch cliphist store &

